openapi: 3.0.0
info:
  title: Spring Session Controller API
  description: API for managing user sessions in a Spring application
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/user/getSession:
    get:
      tags:
        - user
      summary: Retrieve session information
      operationId: getSession
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDataDTO'
  /api/user/setNickname:
    post:
      tags:
        - user
      summary: Set user nickname in session
      operationId: setNickname
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                nickname:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDataDTO'
    x-codegen-request-body-name: nickname
  /api/user/destroySession:
    post:
      tags:
        - user
      summary: Destroy user session
      operationId: destroySession
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
    parameters:
      - in: header
        name: HttpServletRequest
        schema:
          type: string
        required: true
  /api/user/getSessionData:
    get:
      tags:
        - user
      summary: Retrieve session data
      operationId: getSessionData
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDataDTO'
components:
  schemas:
    SessionDataDTO:
      type: object
      properties:
        nickname:
          type: string
        colorPreference:
          type: integer
